//
// Stellarium Scripts
//
// http://github.com/ninadsp/Stellarium-Scripts
//
// Common functions for scripts
//

// Stellarium Script Helper - The object which includes all
// functions and variables
var ssh = ssh || {};

// Objects container
ssh.objects = {};

// Array of planets
ssh.objects.planets = {};

// Array of Messier objects
ssh.objects.M = {};

// Array of constellations
ssh.objects.constellations = {};

// Array of Nebulae
ssh.objects.nebulae = {};

// Array of galaxies
ssh.objects.galaxies = {};

// Array of other objects
ssh.objects.others = {};
